plugins { id 'com.android.application' }

android {
    namespace 'org.lyf.juicesshofflinepro'
    compileSdk 36

    defaultConfig {
        applicationId 'org.lyf.juicesshofflinepro'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    compileOnly files('libs/xposed-api-82-stub.jar')
}
